name: Azure-OIDC-reusable-Example

on: workflow_call

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: nonprd
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.APP_ID }}
        tenant-id: ${{ secrets.TENANT }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - run: |
        echo 'running az account show:'
        az account show
